services:
 streamlit:
    image: ghcr.io/pashitox/nitro-system:latest
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://nitro_user:nitro_pass@postgres:5432/nitro_db

 postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nitro_user
      POSTGRES_PASSWORD: nitro_pass
      POSTGRES_DB: nitro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

 grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data: